---

- hosts: master[0]
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi

- hosts: master[0]
  become: yes
  roles:
    - role: k3s/master

- hosts: master[0]
  roles:
    - role: traefik
      when: deploy_traefik == true | default(false)

- hosts: master[0]
  roles:
    - role: rancher
      when: deploy_rancher == true | default(false)